# -*- coding: utf-8 -*-
"""FinalWeatherPredictionWork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMAmLwECAiXA0LbP5G1DcNmGU5Z3c9Xd
"""

import getWeather
import dataDays
# read dataset to prepare the days 


days = dataDays.Includes()
days = days.getDays()
ModelWeather = getWeather.ModelsPredict(days , [])
WeatherResults, temp , humd , load , wind = ModelWeather.WeatherResults()
print(WeatherResults)
print(temp)
print(humd)
print(load)
print(wind)

# predict the tempreature
# tempreature = ModelWeather.PredictTempreture()
# print(tempreature)
#
# # predict humdidty
# humidity = ModelWeather.predictHumidity()
# print(humidity)
#
# # predict load cover
# loadCover = ModelWeather.predictLoadCover()
# print(loadCover)
#
# # predict wind
# wind = ModelWeather.predictWind()
# print(wind)








